# Generated by Django 4.2.1 on 2023-05-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_inquiries_symptoms_alter_inquiries_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
