# Generated by Django 4.2.1 on 2023-05-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_inquiries_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
