# Generated by Django 4.2.1 on 2023-05-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_treatments'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.inquiries'),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
