# Generated by Django 4.2.1 on 2023-05-29 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_referrals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrals',
            name='ngo',
        ),
        migrations.AddField(
            model_name='referrals',
            name='ngo',
            field=models.ManyToManyField(blank=True, related_name='ngo_referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
