# Generated by Django 4.2.1 on 2023-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_ngo_referrals_ngos'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
