# Generated by Django 4.2.1 on 2023-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_referrals_is_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiries',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
